### PR TITLE
Ayugram

### PR DESCRIPTION
**Pull request by TeaqariaWTF**

### CODE REVIEW

**Comment by cinit** [comment]
I've noticed that Ayugram is a client with R8 obfuscation enabled. Have you checked whether TMoe can work with Ayugram correctly?

**Comment by TeaqariaWTF** [comment]
> Ayugram'ın R8 gizlemenin etkin olduğu bir istemci olduğunu fark ettim. TMoe'nin Ayugram ile doğru şekilde çalışıp çalışmadığını kontrol ettiniz mi?



> I've noticed that Ayugram is a client with R8 obfuscation enabled. Have you checked whether TMoe can work with Ayugram correctly?

Working now with Ayugram

**Comment by TeaqariaWTF** [comment]
> I've noticed that Ayugram is a client with R8 obfuscation enabled. Have you checked whether TMoe can work with Ayugram correctly?

Working now with Ayugram

**Comment by TeaqariaWTF** [comment]
Ayugram will not be supported, right?

**Comment by cinit** [comment]
> Ayugram will not be supported, right?

Compile Ayugram debug apk yourself with R8 obfuscation disabled, and then it should work.

**Pull request merged**
